services:
  vuln1:
    build:
      dockerfile: docker/Dockerfile.vuln1
    ports:
      - "8081:80"
  # vuln2:
  #   build:
  #     dockerfile: docker/Dockerfile.vuln2
  #   ports:
  #     - "3000:3000"
  phoenix:
    image: arizephoenix/phoenix:latest
    ports:
      - 6006:6006  # PHOENIX_PORT
      - 4317:4317  # PHOENIX_GRPC_PORT
    environment:
      - PHOENIX_WORKING_DIR=/mnt/data
    volumes:
      - phoenix_data:/mnt/data  
  app:
    build:
      dockerfile: docker/Dockerfile.app
    ports:
      - "7861:7860"
    develop:
      watch:
        - action: sync
          path: .
          target: /src
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml
volumes:
  phoenix_data:
    driver: local